/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import conexão.ConectaBD;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.Entregador;

/**
 *
 * @author Gabs
 */
public class ListaEntregadores extends javax.swing.JFrame {

    /**
     * Creates new form ListaEntregadores
     */
    public ListaEntregadores() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btMostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTabelaEntregadores = new javax.swing.JTable();
        rtTitulo = new javax.swing.JLabel();
        cxPesquisa = new javax.swing.JTextField();
        btPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Entregadores");

        btMostrar.setText("Mostar Todos");
        btMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMostrarActionPerformed(evt);
            }
        });

        tbTabelaEntregadores.setAutoCreateRowSorter(true);
        tbTabelaEntregadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbTabelaEntregadores);

        rtTitulo.setText("Digite o nome:");

        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtTitulo)
                                .addGap(18, 18, 18)
                                .addComponent(cxPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(btPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(btMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtTitulo)
                    .addComponent(cxPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btMostrar)
                    .addComponent(btPesquisar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMostrarActionPerformed
        List<Entregador> lent = new ArrayList<Entregador>();
        DefaultTableModel modelo = (DefaultTableModel) tbTabelaEntregadores.getModel();
        modelo.setRowCount(0);
        
        ConectaBD banco = new ConectaBD();
        boolean con = banco.getConnection();
        if(con == true){
            try {
                PreparedStatement pst = banco.connection.prepareStatement("SELECT * FROM entregador ORDER BY codigo");
                ResultSet rst = pst.executeQuery();
                while(rst.next()){
                    Entregador ent = new Entregador();
                    
                    ent.setCodigo(rst.getInt("codigo"));
                    ent.setNome(rst.getString("nome"));
                    
                    lent.add(ent);
                }
                for(int i = 0; i<=lent.size(); i++){
                    modelo.insertRow(i, new Object[]{lent.get(i).getCodigo(), lent.get(i).getNome()});
                }
                pst.close();
                rst.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro de Consulta\n"+ex.toString());
            }
            banco.close();
        }
        else{
            JOptionPane.showMessageDialog(null, "Erro de conexão com o banco de dados");
        }
        
    }//GEN-LAST:event_btMostrarActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        List<Entregador> lent = new ArrayList<Entregador>();
        DefaultTableModel modelo = (DefaultTableModel) tbTabelaEntregadores.getModel();
        modelo.setRowCount(0);
        
        ConectaBD banco = new ConectaBD();
        boolean con = banco.getConnection();
        if(con == true){
            try {
                PreparedStatement pst = banco.connection.prepareStatement("SELECT * FROM entregador WHERE nome LIKE '%"+cxPesquisa.getText()+"%' ORDER BY codigo");
                ResultSet rst = pst.executeQuery();
                while(rst.next()){
                    Entregador ent = new Entregador();
                    
                    ent.setCodigo(rst.getInt("codigo"));
                    ent.setNome(rst.getString("nome"));
                    
                    lent.add(ent);
                }
                for(int i = 0; i<=lent.size(); i++){
                    modelo.insertRow(i, new Object[]{lent.get(i).getCodigo(), lent.get(i).getNome()});
                }
                pst.close();
                rst.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro de Consulta\n"+ex.toString());
            }
            banco.close();
        }
        else{
            JOptionPane.showMessageDialog(null, "Erro de conexão com o banco de dados");
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaEntregadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaEntregadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaEntregadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaEntregadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaEntregadores().setVisible(true);
            }
        });
    }
    
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.jpeg")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btMostrar;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JTextField cxPesquisa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rtTitulo;
    private javax.swing.JTable tbTabelaEntregadores;
    // End of variables declaration//GEN-END:variables
}
