/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import conexão.ConectaBD;
import java.awt.Toolkit;
import static java.awt.event.KeyEvent.*;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabs
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtLogo = new javax.swing.JLabel();
        rtUsuario = new javax.swing.JLabel();
        cxUsuario = new javax.swing.JTextField();
        rtSenha = new javax.swing.JLabel();
        cxSenha = new javax.swing.JPasswordField();
        btLogar = new javax.swing.JButton();
        rtFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Login");
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        rtLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\OneDrive\\Documentos\\UTFPR\\2021 - semestre 1\\Programação Desktop\\ProjetoPD\\src\\main\\java\\view\\logo.jpeg")); // NOI18N
        getContentPane().add(rtLogo);
        rtLogo.setBounds(568, 0, 230, 240);

        rtUsuario.setBackground(new java.awt.Color(0, 0, 0));
        rtUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rtUsuario.setForeground(new java.awt.Color(0, 0, 0));
        rtUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rtUsuario.setText("Usuário:");
        getContentPane().add(rtUsuario);
        rtUsuario.setBounds(568, 270, 230, 30);

        cxUsuario.setBackground(new java.awt.Color(102, 102, 255));
        cxUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cxUsuario.setForeground(new java.awt.Color(0, 0, 0));
        cxUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cxUsuario.setBorder(new javax.swing.border.MatteBorder(null));
        cxUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cxUsuarioKeyPressed(evt);
            }
        });
        getContentPane().add(cxUsuario);
        cxUsuario.setBounds(568, 330, 230, 30);

        rtSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rtSenha.setForeground(new java.awt.Color(0, 0, 0));
        rtSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rtSenha.setText("Senha:");
        getContentPane().add(rtSenha);
        rtSenha.setBounds(568, 390, 230, 30);

        cxSenha.setBackground(new java.awt.Color(102, 102, 255));
        cxSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cxSenha.setForeground(new java.awt.Color(0, 0, 0));
        cxSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cxSenha.setBorder(new javax.swing.border.MatteBorder(null));
        cxSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cxSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(cxSenha);
        cxSenha.setBounds(568, 450, 230, 30);

        btLogar.setBackground(new java.awt.Color(102, 102, 255));
        btLogar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btLogar.setForeground(new java.awt.Color(0, 0, 0));
        btLogar.setText("Logar");
        btLogar.setBorder(new javax.swing.border.MatteBorder(null));
        btLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogarActionPerformed(evt);
            }
        });
        getContentPane().add(btLogar);
        btLogar.setBounds(645, 510, 76, 30);

        rtFundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\OneDrive\\Documentos\\UTFPR\\2021 - semestre 1\\Programação Desktop\\ProjetoPD\\src\\main\\java\\view\\fundo.jpg")); // NOI18N
        getContentPane().add(rtFundo);
        rtFundo.setBounds(0, 0, 1366, 768);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogarActionPerformed
        logar();
        limpar();
    }//GEN-LAST:event_btLogarActionPerformed

    private void cxUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cxUsuarioKeyPressed
        if(evt.getKeyCode() == VK_ENTER){
            logar();
            cxSenha.requestFocus();
        }    
    }//GEN-LAST:event_cxUsuarioKeyPressed

    private void cxSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cxSenhaKeyPressed
        if(evt.getKeyCode() == VK_ENTER){
            logar(); 
            limpar();
        }
    }//GEN-LAST:event_cxSenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
    public void logar(){
        ConectaBD banco = new ConectaBD();
        boolean con = banco.getConnection();
        boolean login = false;
        if (con == true){
            try {
                PreparedStatement pst = banco.connection.prepareStatement("SELECT usuario FROM login WHERE usuario=? AND senha=?");
                pst.setString(1, cxUsuario.getText());
                pst.setString(2, cxSenha.getText());
                ResultSet rst = pst.executeQuery();
                if(rst.next()){
                    login = true;
                    TelaPrincipal tp = new TelaPrincipal();
                    tp.setVisible(true);
                    dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Usuário ou senha inválidos");
                }
                rst.close();
                pst.close();
            } 
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro: " + ex.toString());
            }
            banco.close();
        }
        else{
            JOptionPane.showMessageDialog(null, "Não foi possível se conectar ao banco de dados");
            System.exit(0);
        }
    }
    
    public void limpar(){
        cxUsuario.setText("");
        cxSenha.setText("");
        cxUsuario.requestFocus();
    }
    
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.jpeg")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLogar;
    private javax.swing.JPasswordField cxSenha;
    private javax.swing.JTextField cxUsuario;
    private javax.swing.JLabel rtFundo;
    private javax.swing.JLabel rtLogo;
    private javax.swing.JLabel rtSenha;
    private javax.swing.JLabel rtUsuario;
    // End of variables declaration//GEN-END:variables
}
