/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Toolkit;
import javax.swing.JOptionPane;
import modelo.Entregador;
import modelo.Veiculo;


/**
 *
 * @author Gabs
 */
public class TelaPrincipal extends javax.swing.JFrame {

    Entregador entregador = new Entregador();
    Veiculo veiculo = new Veiculo();
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtLogo = new javax.swing.JLabel();
        rtTitulo = new javax.swing.JLabel();
        rtFundo = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        menuEntregador = new javax.swing.JMenu();
        menuRegEnt = new javax.swing.JMenuItem();
        menuListEnt = new javax.swing.JMenuItem();
        menuDelEnt = new javax.swing.JMenuItem();
        menuVeiculo = new javax.swing.JMenu();
        menuRegVei = new javax.swing.JMenuItem();
        meniListVei = new javax.swing.JMenuItem();
        menuDelVei = new javax.swing.JMenuItem();
        menuUsuario = new javax.swing.JMenu();
        menuRegUser = new javax.swing.JMenuItem();
        menuListUser = new javax.swing.JMenuItem();
        menuDelUser = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();
        subMenuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        rtLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\OneDrive\\Documentos\\UTFPR\\2021 - semestre 1\\Programação Desktop\\ProjetoPD\\src\\main\\java\\view\\logo.jpeg")); // NOI18N
        getContentPane().add(rtLogo);
        rtLogo.setBounds(568, 0, 230, 240);

        rtTitulo.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\OneDrive\\Documentos\\UTFPR\\2021 - semestre 1\\Programação Desktop\\SistemaTransportadora\\src\\view\\titulo.png")); // NOI18N
        getContentPane().add(rtTitulo);
        rtTitulo.setBounds(480, 240, 410, 100);

        rtFundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\OneDrive\\Documentos\\UTFPR\\2021 - semestre 1\\Programação Desktop\\ProjetoPD\\src\\main\\java\\view\\fundo.jpg")); // NOI18N
        getContentPane().add(rtFundo);
        rtFundo.setBounds(0, 0, 1366, 768);

        menu.setBackground(new java.awt.Color(0, 0, 0));
        menu.setBorder(null);
        menu.setForeground(new java.awt.Color(255, 255, 255));

        menuEntregador.setBackground(new java.awt.Color(0, 0, 0));
        menuEntregador.setForeground(new java.awt.Color(255, 255, 255));
        menuEntregador.setText("Entregador");

        menuRegEnt.setText("Registar entregador");
        menuRegEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegEntActionPerformed(evt);
            }
        });
        menuEntregador.add(menuRegEnt);

        menuListEnt.setText("Listar entregadores");
        menuListEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListEntActionPerformed(evt);
            }
        });
        menuEntregador.add(menuListEnt);

        menuDelEnt.setText("Deletar entregador");
        menuDelEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDelEntActionPerformed(evt);
            }
        });
        menuEntregador.add(menuDelEnt);

        menu.add(menuEntregador);

        menuVeiculo.setBackground(new java.awt.Color(0, 0, 0));
        menuVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        menuVeiculo.setText("Veículo");

        menuRegVei.setText("Registrar veículo");
        menuRegVei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegVeiActionPerformed(evt);
            }
        });
        menuVeiculo.add(menuRegVei);

        meniListVei.setText("Listar veículos");
        meniListVei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meniListVeiActionPerformed(evt);
            }
        });
        menuVeiculo.add(meniListVei);

        menuDelVei.setText("Deletar veículo");
        menuDelVei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDelVeiActionPerformed(evt);
            }
        });
        menuVeiculo.add(menuDelVei);

        menu.add(menuVeiculo);

        menuUsuario.setBackground(new java.awt.Color(0, 0, 0));
        menuUsuario.setForeground(new java.awt.Color(255, 255, 255));
        menuUsuario.setText("Usuário");

        menuRegUser.setText("Registrar usuário");
        menuRegUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegUserActionPerformed(evt);
            }
        });
        menuUsuario.add(menuRegUser);

        menuListUser.setText("Listar usuários");
        menuListUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListUserActionPerformed(evt);
            }
        });
        menuUsuario.add(menuListUser);

        menuDelUser.setText("Deletar usuário");
        menuDelUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDelUserActionPerformed(evt);
            }
        });
        menuUsuario.add(menuDelUser);

        menu.add(menuUsuario);

        menuSair.setBackground(new java.awt.Color(0, 0, 0));
        menuSair.setForeground(new java.awt.Color(255, 255, 255));
        menuSair.setText("Sair");

        subMenuSair.setText("Sair");
        subMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuSairActionPerformed(evt);
            }
        });
        menuSair.add(subMenuSair);

        menu.add(menuSair);

        setJMenuBar(menu);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuRegEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegEntActionPerformed
        RegistrarEntregador re = new RegistrarEntregador();
        re.setVisible(true);
    }//GEN-LAST:event_menuRegEntActionPerformed

    private void menuRegVeiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegVeiActionPerformed
        RegistrarVeiculo rv = new RegistrarVeiculo();
        rv.setVisible(true);
    }//GEN-LAST:event_menuRegVeiActionPerformed

    private void menuListEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListEntActionPerformed
        ListaEntregadores listaEnt = new ListaEntregadores();
        listaEnt.setVisible(true);
    }//GEN-LAST:event_menuListEntActionPerformed

    private void menuRegUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegUserActionPerformed
        RegistrarUsuario ru = new RegistrarUsuario();
        ru.setVisible(true);
    }//GEN-LAST:event_menuRegUserActionPerformed

    private void meniListVeiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meniListVeiActionPerformed
        ListaVeiculos listaVei = new ListaVeiculos();
        listaVei.setVisible(true);
    }//GEN-LAST:event_meniListVeiActionPerformed

    private void subMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuSairActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "SAIR", 0);
        if (resp == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_subMenuSairActionPerformed

    private void menuListUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListUserActionPerformed
        ListaUsuarios lu = new ListaUsuarios();
        lu.setVisible(true);
    }//GEN-LAST:event_menuListUserActionPerformed

    private void menuDelEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDelEntActionPerformed
        DeletarEntregador de = new DeletarEntregador();
        de.setVisible(true);
    }//GEN-LAST:event_menuDelEntActionPerformed

    private void menuDelVeiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDelVeiActionPerformed
        DeletarVeiculo dv = new DeletarVeiculo();
        dv.setVisible(true);
    }//GEN-LAST:event_menuDelVeiActionPerformed

    private void menuDelUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDelUserActionPerformed
        DeletarUsuario du = new DeletarUsuario();
        du.setVisible(true);
    }//GEN-LAST:event_menuDelUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.jpeg")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem meniListVei;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem menuDelEnt;
    private javax.swing.JMenuItem menuDelUser;
    private javax.swing.JMenuItem menuDelVei;
    private javax.swing.JMenu menuEntregador;
    private javax.swing.JMenuItem menuListEnt;
    private javax.swing.JMenuItem menuListUser;
    private javax.swing.JMenuItem menuRegEnt;
    private javax.swing.JMenuItem menuRegUser;
    private javax.swing.JMenuItem menuRegVei;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenu menuUsuario;
    private javax.swing.JMenu menuVeiculo;
    private javax.swing.JLabel rtFundo;
    private javax.swing.JLabel rtLogo;
    private javax.swing.JLabel rtTitulo;
    private javax.swing.JMenuItem subMenuSair;
    // End of variables declaration//GEN-END:variables
}
